---
- name: Déploiement Flask via CI/CD
  hosts: all
  become: true

  tasks:
    - name: Mettre à jour les paquets
      apt:
        update_cache: yes

    - name: Installer Python et pip
      apt:
        name:
          - python3
          - python3-pip
        state: present

    - name: Cloner le repo Flask
      git:
        repo: 'https://github.com/AlainZen/Ansible-Projects.git'
        dest: /var/www/flask_app
        version: main

    - name: Installer les dépendances Flask
      pip:
        requirements: /var/www/flask_app/01-Flask-Deployment-Ansible/flask_app/requirements.txt

    - name: Lancer l'application Flask
      shell: |
        nohup python3 /var/www/flask_app/01-Flask-Deployment-Ansible/flask_app/app.py &
