name: Security Audit

on:
  push:
    branches:
      - main

jobs:
  security_audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Run Security Audit
        run: |
          ansible-playbook -i inventories/hosts playbooks/security_audit.yml
