---
- name: Déployer une application Flask
  hosts: all
  become: true

  tasks:
    - name: Mettre à jour les paquets
      apt:
        update_cache: yes

    - name: Installer Python et pip
      apt:
        name:
          - python3
          - python3-pip
        state: present

    - name: Créer un dossier pour l'app Flask
      file:
        path: /var/www/flask_app
        state: directory

    - name: Copier l'application Flask
      copy:
        src: ../flask_app/
        dest: /var/www/flask_app/

    - name: Installer les dépendances Flask
      pip:
        requirements: /var/www/flask_app/requirements.txt

    - name: Lancer l'application Flask
      shell: |
        nohup python3 /var/www/flask_app/app.py &
