name: CI/CD Pipeline Flask

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Run Flask Deployment Playbook
        run: |
          ansible-playbook -i 01-Flask-Deployment-Ansible/inventories/hosts 01-Flask-Deployment-Ansible/playbooks/deploy_flask.yml
